"""Customer-first owner management with batch device assignment."""
USERS_WIDGET = r'''
<section id="fg-direct-users">
 <h2 id="fgdu-title"></h2><p id="fgdu-help"></p>
 <div class="fgdu-block"><h3 id="fgdu-create-title"></h3><form id="fgdu-create"><div class="fgdu-field"><label id="fgdu-name-label" for="fgdu-name"></label><input id="fgdu-name" autocomplete="off" placeholder="username" pattern="[a-zA-Z0-9][a-zA-Z0-9._-]{2,63}" minlength="3" maxlength="64" required dir="ltr"></div><div class="fgdu-field"><label id="fgdu-display-label" for="fgdu-display"></label><input id="fgdu-display" maxlength="120"></div><div class="fgdu-field"><label id="fgdu-password-label" for="fgdu-password"></label><div class="fgdu-password-row"><input id="fgdu-password" type="password" autocomplete="new-password" minlength="12" maxlength="128" dir="ltr" aria-describedby="fgdu-password-help"><button type="button" id="fgdu-show-password" aria-controls="fgdu-password" aria-pressed="false"></button></div><small id="fgdu-password-help"></small></div><button id="fgdu-create-button"></button></form>
 <pre id="fgdu-secret" style="white-space:pre-wrap;overflow-wrap:anywhere" dir="ltr"></pre><button type="button" id="fgdu-clear-secret"></button></div>
 <div class="fgdu-block"><h3 id="fgdu-account-title"></h3><select id="fgdu-user" aria-label="User"></select><p id="fgdu-summary"></p><div id="fgdu-assigned"></div>
 <div class="fgdu-actions"><button type="button" id="fgdu-disable"></button><button type="button" id="fgdu-reset"></button></div></div>
 <div class="fgdu-block"><h3 id="fgdu-permission-title"></h3><p id="fgdu-batch-help"></p>
 <div id="fgdu-devices" class="fgdu-device-list"></div>
 <label id="fgdu-macs-label" for="fgdu-macs"></label><textarea id="fgdu-macs" rows="4" dir="ltr" placeholder="2CE032C7A520&#10;AABBCCDDEEFF"></textarea>
 <div class="fgdu-selection"><select id="fgdu-role"></select></div><div id="fgdu-outlets"></div>
 <div class="fgdu-actions"><button type="button" id="fgdu-save"></button></div>
 <details class="fgdu-advanced"><summary id="fgdu-advanced-title"></summary><div class="fgdu-selection"><select id="fgdu-device" aria-label="Device MAC" dir="ltr"></select><button type="button" id="fgdu-load"></button><button type="button" id="fgdu-revoke"></button></div><p id="fgdu-device-help" role="status"></p></details>
 </div><p id="fgdu-status" role="status" aria-live="polite"></p>
</section>
<style>
#fg-direct-users{font:inherit}#fg-direct-users input[type=checkbox]{width:20px;height:20px;min-height:20px;accent-color:#76c5ff}#fg-direct-users button{cursor:pointer}#fg-direct-users button:disabled{opacity:.5;cursor:default}
#fg-direct-users textarea{width:100%;resize:vertical;margin:8px 0 16px;font:16px/1.7 monospace;padding:12px;color:#eff5f8;background:#0d1723;border:1px solid #607890;border-radius:8px}
.fgdu-device-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px;margin:12px 0 18px}.fgdu-device-list label{display:flex;align-items:center;gap:10px;border:1px solid #4b627a;border-radius:8px;padding:10px;background:#182738;overflow-wrap:anywhere}.fgdu-device-list bdi{font-family:monospace}
#fgdu-assigned{display:flex;flex-wrap:wrap;gap:8px}#fgdu-assigned span{padding:5px 10px;border:1px solid #648ba8;border-radius:7px;background:#1b3449;font:14px monospace}.fgdu-advanced{margin-top:18px;border-top:1px solid #3d5268;padding-top:12px}.fgdu-advanced summary{cursor:pointer;color:#a9bacb}.fgdu-advanced .fgdu-selection{margin-top:12px}
</style>
<script>
(()=>{
const root=document.getElementById('fg-direct-users');if(!root)return;
const $=id=>root.querySelector('#fgdu-'+id),t=(ar,en)=>document.documentElement.dir==='rtl'||document.documentElement.lang.startsWith('ar')?ar:en;
let users=[],devices=[],busy=false,selectAfter=null;
function text(id,ar,en){$(id).textContent=t(ar,en)}
function labels(){
text('title','المستخدمون ومجموعات المشتركات','Users and device groups');
text('help','أنشئ حساب العميل مرة واحدة، ثم اربط جميع مشتركاتِه دفعة واحدة. أرسل له بيانات حسابه فقط، وليس دخول المالك.','Create each customer account once, then assign all their devices together. Share only their own account credentials.');
text('create-title','١ · إضافة مستخدم','1 · Add user');text('create-button','إنشاء الحساب','Create account');$('display').placeholder=t('اسم العميل الظاهر','Customer display name');$('display').setAttribute('aria-label',t('اسم العميل الظاهر','Customer display name'));$('name').setAttribute('aria-label',t('اسم الدخول','Login username'));
text('name-label','اسم الدخول','Login username');text('display-label','اسم العميل','Customer name');text('password-label','كلمة المرور','Password');text('password-help','أدخل 12 حرفًا على الأقل، أو اتركها فارغة لتوليد كلمة مرور تلقائيًا. ستظهر بيانات الدخول بعد إنشاء الحساب.','Enter at least 12 characters, or leave blank to generate a password. Login credentials appear after account creation.');$('password').placeholder=t('كلمة مرور اختيارية — 12 حرفًا على الأقل','Optional password — at least 12 characters');text('show-password',$('password').type==='password'?'إظهار':'إخفاء',$('password').type==='password'?'Show':'Hide');
text('account-title','٢ · اختر المستخدم ومجموعته','2 · Select user and their group');text('permission-title','٣ · إضافة مجموعة مشتركات للمستخدم','3 · Assign a group of devices');text('batch-help','اختر عدة مشتركات مسجلة أو الصق عناوين MAC الجديدة أدناه. الصلاحيات المختارة ستُطبّق على المجموعة المحددة فقط؛ باقي مشتركات المستخدم تبقى كما هي. بعد تسجيل مشترك جديد اضبط Controller IP فيه على 104.207.95.47.','Select registered devices or paste new MAC addresses below. Permissions apply only to the selected group; other assignments remain unchanged. Provision each new device Controller IP to 104.207.95.47 after registration.');
text('macs-label','عناوين MAC جديدة أو موجودة — كل عنوان في سطر، ويمكن الفصل بفاصلة','New or existing MAC addresses — one per line, or comma separated');text('clear-secret','إخفاء بيانات الدخول','Hide login credentials');text('save','ربط المجموعة وحفظ الصلاحيات','Assign group and save permissions');text('revoke','سحب وصول هذا المشترك','Revoke this device');text('reset','تغيير كلمة المرور وإلغاء الجلسات','Reset password and sessions');text('advanced-title','تعديل مشترك محدد داخل المجموعة','Edit an individual device in the group');text('load','تحميل صلاحياته للتعديل','Load its permissions');
for(const o of $('role').options)o.textContent=o.value==='view'?t('مشاهدة فقط','View only'):t('مشاهدة وتحكم','View and control');
for(let n=1;n<=4;n++){const box=$('outlets').children[n-1];box.querySelector('strong').textContent=t('مخرج ','Outlet ')+n;for(const label of box.querySelectorAll('label'))label.querySelector('span').textContent=label.querySelector('input').id.includes('-v')?t('مشاهدة','View'):t('تحكم','Control')}
}
for(const value of ['control','view']){const o=document.createElement('option');o.value=value;$('role').append(o)}
for(let n=1;n<=4;n++){const box=document.createElement('div'),title=document.createElement('strong');box.append(title);for(const kind of ['v','c']){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.id='fgdu-'+kind+n;input.checked=true;const caption=document.createElement('span');label.style.cssText='all:unset!important;display:grid!important;grid-template-columns:24px minmax(0,1fr)!important;align-items:center!important;gap:12px!important;width:100%!important;min-width:0!important;padding:8px 0!important;margin:0!important;position:static!important;float:none!important;cursor:pointer!important;direction:inherit!important';caption.style.cssText='all:unset!important;display:block!important;min-width:0!important;overflow-wrap:anywhere!important;position:static!important;color:inherit!important';label.append(input,caption);box.append(label);input.onchange=()=>{if(kind==='c'&&input.checked){$('v'+n).checked=true;$('role').value='control'}if(kind==='v'&&!input.checked)$('c'+n).checked=false}}$('outlets').append(box)}
async function api(path,method='GET',body){const r=await fetch('/panel/api/direct/'+path,{method,credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});let j={};try{j=await r.json()}catch(_){}if(!r.ok)throw Error(typeof j.detail==='string'?j.detail:'HTTP '+r.status);return j}
function current(){return users.find(u=>u.id===$('user').value)}
function enable(){$('user').disabled=busy||!users.length;$('macs').disabled=busy||!current();$('role').disabled=busy||!current();$('device').disabled=busy||!$('device').value;for(const id of ['save','disable','reset','load','revoke'])$(id).disabled=busy||!current()||(['load','revoke'].includes(id)&&!$('device').value)}
function chosen(){const u=current();$('summary').textContent=u?t('المشتركات المرتبطة: ','Assigned devices: ')+u.grants.length:t('أنشئ حسابًا أو اختر مستخدمًا','Create an account or select a user');$('assigned').replaceChildren();for(const g of u?.grants||[]){const span=document.createElement('span');span.dir='ltr';span.textContent=g.mac;$('assigned').append(span)}$('disable').textContent=u?.active?t('تعطيل الحساب وإلغاء الجلسات','Disable account and sessions'):t('تفعيل الحساب','Enable account');$('device').replaceChildren();for(const g of u?.grants||[]){const o=document.createElement('option');o.value=g.mac;o.textContent=g.mac;$('device').append(o)}if(!$('device').options.length){const o=document.createElement('option');o.value='';o.textContent=u?t('لا توجد مشتركات مرتبطة بهذا المستخدم','No devices assigned to this user'):t('اختر مستخدمًا أولًا','Select a user first');$('device').append(o)}$('device-help').textContent=u?.grants.length?t('اختر المشترك، ثم حمّل صلاحياته للتعديل.','Select a device and load its permissions to edit.'):t('اربط مجموعة المشتركات بالمستخدم باستخدام زر الحفظ أعلاه؛ ستظهر هنا بعد نجاح الربط.','Assign a device group using the save button above; it will appear here after saving.');$('devices').replaceChildren();for(const d of devices){const label=document.createElement('label'),input=document.createElement('input'),code=document.createElement('bdi');input.type='checkbox';input.value=d.mac;code.textContent=d.mac;label.append(input,code);if(u?.grants.some(g=>g.mac===d.mac))label.append(document.createTextNode(t('مرتبط','Assigned')));$('devices').append(label)}enable()}
async function refresh(){const old=selectAfter||$('user').value;selectAfter=null;const [u,d]=await Promise.all([api('users'),api('devices')]);users=u.users||[];devices=d.devices||[];$('user').replaceChildren();for(const user of users){const o=document.createElement('option');o.value=user.id;o.textContent=user.username+' · '+user.display_name+' · '+(user.active?t('فعال','Active'):t('معطل','Disabled'));$('user').append(o)}if(!users.length){const o=document.createElement('option');o.textContent=t('لا يوجد مستخدم — أنشئ حسابًا أولًا','No users — create an account first');o.value='';$('user').append(o)}if(users.some(u=>u.id===old))$('user').value=old;chosen()}
function secret(j){$('secret').textContent=t('احفظ هذه البيانات الآن؛ لن تظهر كلمة المرور مرة أخرى.','Save these credentials now; the password will not be displayed again.')+'\nHTTPS: https://link.fgmachines.org\nUsername: '+j.username+'\nPassword: '+j.password}
async function run(action){if(busy)return;busy=true;root.querySelectorAll('button,input,select,textarea').forEach(e=>e.disabled=true);text('status','جارٍ التنفيذ…','Working…');try{await action();await refresh();text('status','تم حفظ التغيير','Change saved')}catch(e){$('status').textContent=e.message}finally{busy=false;root.querySelectorAll('button,input,select,textarea').forEach(e=>e.disabled=false);enable()}}
$('create').onsubmit=e=>{e.preventDefault();run(async()=>{const body={username:$('name').value.trim(),display_name:$('display').value.trim()};if($('password').value)body.password=$('password').value;const j=await api('users','POST',body);secret(j);selectAfter=j.id;$('name').value='';$('display').value='';$('password').value='';$('password').type='password';$('show-password').setAttribute('aria-pressed','false');labels()})};
$('show-password').onclick=()=>{const show=$('password').type==='password';$('password').type=show?'text':'password';$('show-password').setAttribute('aria-pressed',String(show));labels()};
$('user').onchange=()=>{chosen();$('macs').value='';for(let n=1;n<=4;n++){$('v'+n).checked=true;$('c'+n).checked=true}$('role').value='control'};
$('role').onchange=()=>{for(let n=1;n<=4;n++)$('c'+n).checked=$('role').value==='control'&&$('v'+n).checked};
$('save').onclick=()=>run(async()=>{if(!current())throw Error(t('اختر المستخدم أولًا','Select a user first'));const selected=[...$('devices').querySelectorAll('input:checked')].map(e=>e.value);const pasted=$('macs').value.trim().split(/[\s,;،]+/).filter(Boolean);const macs=[...new Set([...selected,...pasted].map(m=>m.toUpperCase()))];if(!macs.length||macs.length>256||macs.some(m=>!/^[0-9A-F]{12}$/.test(m)))throw Error(t('اختر مشتركات أو أدخل عناوين MAC صحيحة، بحد أقصى 256','Select devices or enter valid MAC addresses, up to 256'));let view=0,control=0;for(let n=1;n<=4;n++){if($('v'+n).checked)view|=1<<(n-1);if($('c'+n).checked)control|=1<<(n-1)}if(!view)throw Error(t('اختر مخرجًا واحدًا للمشاهدة على الأقل','Select at least one visible outlet'));await api('users/'+encodeURIComponent(current().id)+'/devices','PUT',{macs,view_mask:view,control_mask:control});$('macs').value=''});
$('load').onclick=()=>{const g=current()?.grants.find(g=>g.mac===$('device').value);if(!g)return;for(let n=1;n<=4;n++){$('v'+n).checked=!!(g.view_mask&(1<<(n-1)));$('c'+n).checked=!!(g.control_mask&(1<<(n-1)))}$('role').value=g.control_mask?'control':'view';$('macs').value='';for(const input of $('devices').querySelectorAll('input'))input.checked=input.value===g.mac;text('status','تم تحميل صلاحيات هذا المشترك؛ عدّلها ثم احفظ المجموعة','Device permissions loaded; edit them and save the group')};
$('revoke').onclick=()=>run(async()=>{if(!current()||!$('device').value)throw Error(t('اختر مستخدمًا ومشتركًا','Select a user and device'));await api('users/'+current().id+'/devices/'+$('device').value,'DELETE')});
$('disable').onclick=()=>run(async()=>{if(!current())throw Error(t('اختر مستخدمًا','Select a user'));await api('users/'+current().id,'PATCH',{active:!current().active})});
$('reset').onclick=()=>run(async()=>{if(!current())throw Error(t('اختر مستخدمًا','Select a user'));secret(await api('users/'+current().id+'/reset-password','POST'))});$('clear-secret').onclick=()=>{$('secret').textContent=''};
labels();new MutationObserver(()=>{labels();chosen()}).observe(document.documentElement,{attributes:true,attributeFilter:['dir','lang']});refresh().catch(e=>{$('status').textContent=e.message});
})();
</script>
'''
